-   id: validate_manifest
    name: Validate Pre-Commit Manifest
    description: This validator validates a pre-commit hooks manifest file
    entry: pre-commit-validate-manifest
    language: python
    files: ^(\.pre-commit-hooks\.yaml|hooks\.yaml)$
-   id: autopep8
    name: autopep8
    entry: autopep8
    language: python
    'types': [python]
    args: ["-i"]
    require_serial: false
    additional_dependencies: []
